package com.itson.bdavanzadas.banco;

import com.itson.bdavanzadas.bancopersistencia.daos.ICuentasDAO;

public class DlgFolioGenerado extends javax.swing.JDialog {

    private final ICuentasDAO cuentasDAO;
    
    public DlgFolioGenerado(java.awt.Frame parent, boolean modal,ICuentasDAO cuentasDAO) {
        super(parent, modal);
        initComponents();
        this.cuentasDAO = cuentasDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelUsuarioRegistro2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        labelContrasena = new javax.swing.JLabel();
        labelUsuarioRegistro4 = new javax.swing.JLabel();
        labelFolio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 223, 148));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Los datos generados para el retiro son los siguientes");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        labelUsuarioRegistro2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelUsuarioRegistro2.setText("Contraseña:");
        bg.add(labelUsuarioRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, -1));

        btnAceptar.setBackground(new java.awt.Color(255, 204, 102));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(100, 100, 100));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        bg.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 110, -1));

        labelContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bg.add(labelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 220, 20));

        labelUsuarioRegistro4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelUsuarioRegistro4.setText("Folio:");
        bg.add(labelUsuarioRegistro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, -1));

        labelFolio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bg.add(labelFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelFolio;
    private javax.swing.JLabel labelUsuarioRegistro2;
    private javax.swing.JLabel labelUsuarioRegistro4;
    // End of variables declaration//GEN-END:variables
}
