/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.bdavanzadas.banco;

/**
 *
 * @author renec
 */
public class RegistroForm extends javax.swing.JFrame {

    /**
     * Creates new form registroForm
     */
    public RegistroForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        R = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelUsuarioRegistro = new javax.swing.JLabel();
        labelEmailRegistro = new javax.swing.JLabel();
        labelContraseñaRegistro = new javax.swing.JLabel();
        botonRegistrarUsuario = new javax.swing.JButton();
        campoTextoNombreUsuario = new javax.swing.JTextField();
        campoTextoEmailUsuario = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        campoTextoTelefonoUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        campoTextoContrasena = new javax.swing.JPasswordField();
        campoTextoContrasenaConfirmacion = new javax.swing.JPasswordField();
        labelContraseñaRegistro1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        L = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        R.setBackground(new java.awt.Color(255, 255, 255));
        R.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setBackground(new java.awt.Color(255, 223, 148));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 223, 148));
        jLabel2.setText("Registrar Usuario");

        labelUsuarioRegistro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelUsuarioRegistro.setText("Nombre:");

        labelEmailRegistro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelEmailRegistro.setText("Fecha Nacimiento:");

        labelContraseñaRegistro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelContraseñaRegistro.setText("Contraseña:");

        botonRegistrarUsuario.setBackground(new java.awt.Color(255, 223, 148));
        botonRegistrarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        botonRegistrarUsuario.setForeground(new java.awt.Color(100, 100, 100));
        botonRegistrarUsuario.setText("Registrar usuario");
        botonRegistrarUsuario.setBorder(null);
        botonRegistrarUsuario.setBorderPainted(false);
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });

        campoTextoNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoTextoNombreUsuario.setForeground(new java.awt.Color(100, 100, 100));
        campoTextoNombreUsuario.setBorder(null);
        campoTextoNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNombreUsuarioActionPerformed(evt);
            }
        });

        campoTextoEmailUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoTextoEmailUsuario.setForeground(new java.awt.Color(100, 100, 100));
        campoTextoEmailUsuario.setBorder(null);
        campoTextoEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEmailUsuarioActionPerformed(evt);
            }
        });

        labelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelTelefono.setText("Domicilio:");

        campoTextoTelefonoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoTextoTelefonoUsuario.setForeground(new java.awt.Color(100, 100, 100));
        campoTextoTelefonoUsuario.setBorder(null);

        campoTextoContrasena.setForeground(new java.awt.Color(100, 100, 100));
        campoTextoContrasena.setBorder(null);

        campoTextoContrasenaConfirmacion.setForeground(new java.awt.Color(100, 100, 100));
        campoTextoContrasenaConfirmacion.setBorder(null);

        labelContraseñaRegistro1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelContraseñaRegistro1.setText("Confirmar contraseña:");

        javax.swing.GroupLayout RLayout = new javax.swing.GroupLayout(R);
        R.setLayout(RLayout);
        RLayout.setHorizontalGroup(
            RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RLayout.createSequentialGroup()
                .addGroup(RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2))
                    .addGroup(RLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoContrasenaConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelTelefono)
                                .addComponent(labelEmailRegistro)
                                .addComponent(labelUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoTextoNombreUsuario)
                                .addComponent(campoTextoEmailUsuario)
                                .addComponent(campoTextoTelefonoUsuario)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator6)
                                .addComponent(jSeparator4)
                                .addComponent(campoTextoContrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                .addComponent(labelContraseñaRegistro)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(labelContraseñaRegistro1)))
                    .addGroup(RLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        RLayout.setVerticalGroup(
            RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuarioRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEmailRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoTextoEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelContraseñaRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContraseñaRegistro1)
                .addGap(1, 1, 1)
                .addComponent(campoTextoContrasenaConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        bg.add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        L.setBackground(new java.awt.Color(255, 223, 148));
        L.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("© [2023] SCAA. Todos los derechos reservados.\"");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Somos tu banco de confianza!!");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tu dinero, siempre en tus manos");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LLayout = new javax.swing.GroupLayout(L);
        L.setLayout(LLayout);
        LLayout.setHorizontalGroup(
            LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LLayout.createSequentialGroup()
                .addGap(0, 269, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LLayout.createSequentialGroup()
                        .addComponent(botonCancelar)
                        .addGap(30, 30, 30))))
            .addGroup(LLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LLayout.setVerticalGroup(
            LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCancelar)
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(53, 53, 53))
        );

        bg.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed

    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    private void campoTextoNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNombreUsuarioActionPerformed

    private void campoTextoEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEmailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEmailUsuarioActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        
    }//GEN-LAST:event_botonCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel L;
    private javax.swing.JPanel R;
    private javax.swing.JPanel bg;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JPasswordField campoTextoContrasena;
    private javax.swing.JPasswordField campoTextoContrasenaConfirmacion;
    private javax.swing.JTextField campoTextoEmailUsuario;
    private javax.swing.JTextField campoTextoNombreUsuario;
    private javax.swing.JTextField campoTextoTelefonoUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelContraseñaRegistro;
    private javax.swing.JLabel labelContraseñaRegistro1;
    private javax.swing.JLabel labelEmailRegistro;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
